# Site Settings

title: Zajac Teaching Portfolio
email: zajac@uark.edu
description: >
  This is a portfolio of teaching matierials for Mark Zajac, including
  a video recording of a lecture on magnetic induction.  Pre-lecture
  materials include a video demonstration, along with class notes for
  studetnts and instructors.  Post-lecture materials include a booklet
  of drill excercies, a booklet of homework excercies and a test.
baseurl: ""
url: "http://Old-Faithful:4000"

# Build Settings

markdown: kramdown

sass:
  sass_dir: _sass
include: ['_pages']

kramdown:
  input: GFM
